import './js/toggleLang';
import './js/descr_job_vacancy';
import './js/slider_licenses';
import './js/slider_reviews';
import './js/expand_answer_question';
import './js/openMobileMenu';
import './js/openSocialListClinic';
import './js/openLocationBlockClinic';
import './js/openModalContacts';
import './js/scrollUp';
import './js/openModaWindowMap';
import './js/openModaWindowLicenes';
import './js/openModaWindowVideo';
import './js/openModaWindowForm';
import './js/showDetailsMedicalCard';
// import './js/anime';
